version: "3.7"
services:
  trello-utils-mono:
    build:
      context: .
      dockerfile: production.Dockerfile
    environment:
      RAILS_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: bash production-start.sh
